### ISSUE TITLE
[JENKINS-67441] java.lang.ClassNotFoundException: javax.ws.rs.ext.MessageBodyReader after update to 2.319.1

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/workflow-cps-plugin#1619]
<p>I've updated Jenkins to version 2.319.1 (from 2.289.3). Since this update the multibranch pipeline isn't cleared anymore (see multibranch.png).</p>

<p>The Multibranch Pipeline Log seems to be correct, however the branch isn't removed.</p>

<pre>
Evaluating orphaned items in test
Will remove feature/TTT-999
Finished: NOT_BUILT
</pre>
<p>  I didn't change the Orphaned Item Strategy for this project.</p>

<p> </p>

<p> </p>

<p> </p>

<p>Since the update I find a lot of exceptions "java.lang.ClassNotFoundException: javax.ws.rs.ext.MessageBodyReader" in the error log.</p>

<pre>
2021-12-21 06:05:47.544+0000 [id=19650] INFO o.j.p.workflow.job.WorkflowRun#finish: ZCC/PR-4104 #15 completed: FAILURE
2021-12-21 06:05:47.566+0000 [id=19650] WARNING h.model.listeners.RunListener#report: RunListener failedjava.lang.ClassNotFoundException: javax.ws.rs.ext.MessageBodyReader at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1417) at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1372) at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1127) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source)Caused: java.lang.NoClassDefFoundError: javax/ws/rs/ext/MessageBodyReader at java.lang.<span class="code-object">ClassLoader</span>.defineClass1(Native Method) at java.lang.<span class="code-object">ClassLoader</span>.defineClass(Unknown Source) at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1187) at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1355) at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1407) at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1372) at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1127) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source) at java.lang.<span class="code-object">ClassLoader</span>.defineClass1(Native Method) at java.lang.<span class="code-object">ClassLoader</span>.defineClass(Unknown Source) at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1187) at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1355) at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1407) at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1372) at jenkins.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:107) at hudson.ClassicPluginStrategy$DependencyClassLoader.findClass(ClassicPluginStrategy.java:646) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source) at jenkins.util.AntClassLoader.findBaseClass(AntClassLoader.java:1436) at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1123) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source) at java.lang.<span class="code-object">Class</span>.forName0(Native Method) at java.lang.<span class="code-object">Class</span>.forName(Unknown Source) at com.sun.jersey.core.reflection.ReflectionHelper$3.run(ReflectionHelper.java:289) at com.sun.jersey.core.reflection.ReflectionHelper$3.run(ReflectionHelper.java:279) at java.security.AccessController.doPrivileged(Native Method) at com.sun.jersey.spi.service.ServiceFinder$AbstractLazyIterator.hasNext(ServiceFinder.java:697) at com.sun.jersey.spi.service.ServiceFinder.toClassArray(ServiceFinder.java:549) at com.sun.jersey.core.spi.component.ProviderServices.getServiceClasses(ProviderServices.java:345) at com.sun.jersey.core.spi.component.ProviderServices.getServiceClasses(ProviderServices.java:338) at com.sun.jersey.core.spi.component.ProviderServices.getServices(ProviderServices.java:162) at com.sun.jersey.core.spi.factory.MessageBodyFactory.initReaders(MessageBodyFactory.java:176) at com.sun.jersey.core.spi.factory.MessageBodyFactory.init(MessageBodyFactory.java:162) at com.sun.jersey.api.client.Client.init(Client.java:343) at com.sun.jersey.api.client.Client.access$000(Client.java:119) at com.sun.jersey.api.client.Client$1.f(Client.java:192) at com.sun.jersey.api.client.Client$1.f(Client.java:188) at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193) at com.sun.jersey.api.client.Client.<init>(Client.java:188) at com.sun.jersey.api.client.Client.<init>(Client.java:171) at com.sun.jersey.api.client.Client.create(Client.java:683) at org.marvelution.jji.JIRAUtils.createClient(JIRAUtils.java:82) at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(Unknown Source) at java.lang.ThreadLocal.setInitialValue(Unknown Source) at java.lang.ThreadLocal.get(Unknown Source) at org.marvelution.jji.SitesClient.getResource(SitesClient.java:209) at org.marvelution.jji.SitesClient.getResource(SitesClient.java:217) at org.marvelution.jji.SitesClient.getResource(SitesClient.java:213) at org.marvelution.jji.SitesClient.lambda$notifyBuildCompleted$1(SitesClient.java:71) at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) at java.util.stream.AbstractPipeline.copyInto(Unknown Source) at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) at java.util.stream.AbstractPipeline.evaluate(Unknown Source) at java.util.stream.ReferencePipeline.forEach(Unknown Source) at org.marvelution.jji.SitesClient.doWithSites(SitesClient.java:201) at org.marvelution.jji.SitesClient.doWithSites(SitesClient.java:197) at org.marvelution.jji.SitesClient.notifyBuildCompleted(SitesClient.java:69) at org.marvelution.jji.listener.BuildListener.onCompleted(BuildListener.java:45) at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:208) at org.jenkinsci.plugins.workflow.job.WorkflowRun.finish(WorkflowRun.java:625) at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:361) at hudson.model.ResourceController.execute(ResourceController.java:99) at hudson.model.Executor.run(Executor.java:432)
</pre>
<p> </p>

<pre>
2021-12-23 07:25:52.632+0000 [id=34110] WARNING h.model.listeners.RunListener#report: RunListener failed
2021-12-23 07:25:52.632+0000 [id=34110] WARNING h.model.listeners.RunListener#report: RunListener failedjava.lang.ClassNotFoundException: javax.ws.rs.ext.MessageBodyReader at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1417) at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1372) at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1127) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source)Caused: java.lang.NoClassDefFoundError: javax/ws/rs/ext/MessageBodyReader at java.lang.<span class="code-object">ClassLoader</span>.defineClass1(Native Method) at java.lang.<span class="code-object">ClassLoader</span>.defineClass(Unknown Source) at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1187) at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1355) at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1407) at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1372) at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1127) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source) at java.lang.<span class="code-object">ClassLoader</span>.defineClass1(Native Method) at java.lang.<span class="code-object">ClassLoader</span>.defineClass(Unknown Source) at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1187) at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1355) at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1407) at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1372) at jenkins.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:107) at hudson.ClassicPluginStrategy$DependencyClassLoader.findClass(ClassicPluginStrategy.java:646) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source) at jenkins.util.AntClassLoader.findBaseClass(AntClassLoader.java:1436) at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1123) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source) at java.lang.<span class="code-object">Class</span>.forName0(Native Method) at java.lang.<span class="code-object">Class</span>.forName(Unknown Source) at com.sun.jersey.core.reflection.ReflectionHelper$3.run(ReflectionHelper.java:289) at com.sun.jersey.core.reflection.ReflectionHelper$3.run(ReflectionHelper.java:279) at java.security.AccessController.doPrivileged(Native Method) at com.sun.jersey.spi.service.ServiceFinder$AbstractLazyIterator.hasNext(ServiceFinder.java:697) at com.sun.jersey.spi.service.ServiceFinder.toClassArray(ServiceFinder.java:549) at com.sun.jersey.core.spi.component.ProviderServices.getServiceClasses(ProviderServices.java:345) at com.sun.jersey.core.spi.component.ProviderServices.getServiceClasses(ProviderServices.java:338) at com.sun.jersey.core.spi.component.ProviderServices.getServices(ProviderServices.java:162) at com.sun.jersey.core.spi.factory.MessageBodyFactory.initReaders(MessageBodyFactory.java:176) at com.sun.jersey.core.spi.factory.MessageBodyFactory.init(MessageBodyFactory.java:162) at com.sun.jersey.api.client.Client.init(Client.java:343) at com.sun.jersey.api.client.Client.access$000(Client.java:119) at com.sun.jersey.api.client.Client$1.f(Client.java:192) at com.sun.jersey.api.client.Client$1.f(Client.java:188) at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193) at com.sun.jersey.api.client.Client.<init>(Client.java:188) at com.sun.jersey.api.client.Client.<init>(Client.java:171) at com.sun.jersey.api.client.Client.create(Client.java:683) at org.marvelution.jji.JIRAUtils.createClient(JIRAUtils.java:82) at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(Unknown Source) at java.lang.ThreadLocal.setInitialValue(Unknown Source) at java.lang.ThreadLocal.get(Unknown Source) at org.marvelution.jji.SitesClient.getResource(SitesClient.java:209) at org.marvelution.jji.SitesClient.getResource(SitesClient.java:217) at org.marvelution.jji.SitesClient.getResource(SitesClient.java:213) at org.marvelution.jji.SitesClient.lambda$notifyBuildCompleted$1(SitesClient.java:71) at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) at java.util.stream.AbstractPipeline.copyInto(Unknown Source) at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) at java.util.stream.AbstractPipeline.evaluate(Unknown Source) at java.util.stream.ReferencePipeline.forEach(Unknown Source) at org.marvelution.jji.SitesClient.doWithSites(SitesClient.java:201) at org.marvelution.jji.SitesClient.doWithSites(SitesClient.java:197) at org.marvelution.jji.SitesClient.notifyBuildCompleted(SitesClient.java:69) at org.marvelution.jji.listener.BuildListener.onCompleted(BuildListener.java:45) at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:208) at org.jenkinsci.plugins.workflow.job.WorkflowRun.finish(WorkflowRun.java:625) at org.jenkinsci.plugins.workflow.job.WorkflowRun.access$800(WorkflowRun.java:138) at org.jenkinsci.plugins.workflow.job.WorkflowRun$GraphL.onNewHead(WorkflowRun.java:1045) at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1473) at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:491) at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:38) at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139) at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28) at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68) at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) at java.util.concurrent.FutureTask.run(Unknown Source) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.<span class="code-object">Thread</span>.run(Unknown Source)
</pre>
<p>I use JVM 1.8.0_282.</p>

<p>I assume this is a bug because a class can't be found. </p>

<p>Is there a workarround available (because I don't want to downgrade the whole system)?</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=mario_b">mario_b</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-67441" target="_blank">java.lang.ClassNotFoundException: javax.ws.rs.ext.MessageBodyReader after update to 2.319.1</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>component(s)</b>: workflow-cps-plugin
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2022-01-04T06:19:51+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 2025-12-07
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>I've updated Jenkins to version 2.319.1 (from 2.289.3). Since this update the multibranch pipeline isn't cleared anymore (see multibranch.png).</p>

<p>The Multibranch Pipeline Log seems to be correct, however the branch isn't removed.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Evaluating orphaned items in test
Will remove feature/TTT-999
Finished: NOT_BUILT
</pre>
</div></div>
<p>  I didn't change the Orphaned Item Strategy for this project.</p>

<p> </p>

<p> </p>

<p> </p>

<p>Since the update I find a lot of exceptions "java.lang.ClassNotFoundException: javax.ws.rs.ext.MessageBodyReader" in the error log.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2021-12-21 06:05:47.544+0000 [id=19650] INFO o.j.p.workflow.job.WorkflowRun#finish: ZCC/PR-4104 #15 completed: FAILURE
2021-12-21 06:05:47.566+0000 [id=19650] WARNING h.model.listeners.RunListener#report: RunListener failedjava.lang.ClassNotFoundException: javax.ws.rs.ext.MessageBodyReader at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1417) at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1372) at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1127) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source)Caused: java.lang.NoClassDefFoundError: javax/ws/rs/ext/MessageBodyReader at java.lang.<span class="code-object">ClassLoader</span>.defineClass1(Native Method) at java.lang.<span class="code-object">ClassLoader</span>.defineClass(Unknown Source) at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1187) at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1355) at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1407) at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1372) at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1127) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source) at java.lang.<span class="code-object">ClassLoader</span>.defineClass1(Native Method) at java.lang.<span class="code-object">ClassLoader</span>.defineClass(Unknown Source) at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1187) at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1355) at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1407) at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1372) at jenkins.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:107) at hudson.ClassicPluginStrategy$DependencyClassLoader.findClass(ClassicPluginStrategy.java:646) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source) at jenkins.util.AntClassLoader.findBaseClass(AntClassLoader.java:1436) at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1123) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source) at java.lang.<span class="code-object">Class</span>.forName0(Native Method) at java.lang.<span class="code-object">Class</span>.forName(Unknown Source) at com.sun.jersey.core.reflection.ReflectionHelper$3.run(ReflectionHelper.java:289) at com.sun.jersey.core.reflection.ReflectionHelper$3.run(ReflectionHelper.java:279) at java.security.AccessController.doPrivileged(Native Method) at com.sun.jersey.spi.service.ServiceFinder$AbstractLazyIterator.hasNext(ServiceFinder.java:697) at com.sun.jersey.spi.service.ServiceFinder.toClassArray(ServiceFinder.java:549) at com.sun.jersey.core.spi.component.ProviderServices.getServiceClasses(ProviderServices.java:345) at com.sun.jersey.core.spi.component.ProviderServices.getServiceClasses(ProviderServices.java:338) at com.sun.jersey.core.spi.component.ProviderServices.getServices(ProviderServices.java:162) at com.sun.jersey.core.spi.factory.MessageBodyFactory.initReaders(MessageBodyFactory.java:176) at com.sun.jersey.core.spi.factory.MessageBodyFactory.init(MessageBodyFactory.java:162) at com.sun.jersey.api.client.Client.init(Client.java:343) at com.sun.jersey.api.client.Client.access$000(Client.java:119) at com.sun.jersey.api.client.Client$1.f(Client.java:192) at com.sun.jersey.api.client.Client$1.f(Client.java:188) at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193) at com.sun.jersey.api.client.Client.&lt;init&gt;(Client.java:188) at com.sun.jersey.api.client.Client.&lt;init&gt;(Client.java:171) at com.sun.jersey.api.client.Client.create(Client.java:683) at org.marvelution.jji.JIRAUtils.createClient(JIRAUtils.java:82) at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(Unknown Source) at java.lang.ThreadLocal.setInitialValue(Unknown Source) at java.lang.ThreadLocal.get(Unknown Source) at org.marvelution.jji.SitesClient.getResource(SitesClient.java:209) at org.marvelution.jji.SitesClient.getResource(SitesClient.java:217) at org.marvelution.jji.SitesClient.getResource(SitesClient.java:213) at org.marvelution.jji.SitesClient.lambda$notifyBuildCompleted$1(SitesClient.java:71) at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) at java.util.stream.AbstractPipeline.copyInto(Unknown Source) at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) at java.util.stream.AbstractPipeline.evaluate(Unknown Source) at java.util.stream.ReferencePipeline.forEach(Unknown Source) at org.marvelution.jji.SitesClient.doWithSites(SitesClient.java:201) at org.marvelution.jji.SitesClient.doWithSites(SitesClient.java:197) at org.marvelution.jji.SitesClient.notifyBuildCompleted(SitesClient.java:69) at org.marvelution.jji.listener.BuildListener.onCompleted(BuildListener.java:45) at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:208) at org.jenkinsci.plugins.workflow.job.WorkflowRun.finish(WorkflowRun.java:625) at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:361) at hudson.model.ResourceController.execute(ResourceController.java:99) at hudson.model.Executor.run(Executor.java:432)
</pre>
</div></div>
<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2021-12-23 07:25:52.632+0000 [id=34110] WARNING h.model.listeners.RunListener#report: RunListener failed
2021-12-23 07:25:52.632+0000 [id=34110] WARNING h.model.listeners.RunListener#report: RunListener failedjava.lang.ClassNotFoundException: javax.ws.rs.ext.MessageBodyReader at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1417) at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1372) at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1127) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source)Caused: java.lang.NoClassDefFoundError: javax/ws/rs/ext/MessageBodyReader at java.lang.<span class="code-object">ClassLoader</span>.defineClass1(Native Method) at java.lang.<span class="code-object">ClassLoader</span>.defineClass(Unknown Source) at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1187) at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1355) at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1407) at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1372) at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1127) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source) at java.lang.<span class="code-object">ClassLoader</span>.defineClass1(Native Method) at java.lang.<span class="code-object">ClassLoader</span>.defineClass(Unknown Source) at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1187) at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1355) at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1407) at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1372) at jenkins.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:107) at hudson.ClassicPluginStrategy$DependencyClassLoader.findClass(ClassicPluginStrategy.java:646) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source) at jenkins.util.AntClassLoader.findBaseClass(AntClassLoader.java:1436) at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1123) at java.lang.<span class="code-object">ClassLoader</span>.loadClass(Unknown Source) at java.lang.<span class="code-object">Class</span>.forName0(Native Method) at java.lang.<span class="code-object">Class</span>.forName(Unknown Source) at com.sun.jersey.core.reflection.ReflectionHelper$3.run(ReflectionHelper.java:289) at com.sun.jersey.core.reflection.ReflectionHelper$3.run(ReflectionHelper.java:279) at java.security.AccessController.doPrivileged(Native Method) at com.sun.jersey.spi.service.ServiceFinder$AbstractLazyIterator.hasNext(ServiceFinder.java:697) at com.sun.jersey.spi.service.ServiceFinder.toClassArray(ServiceFinder.java:549) at com.sun.jersey.core.spi.component.ProviderServices.getServiceClasses(ProviderServices.java:345) at com.sun.jersey.core.spi.component.ProviderServices.getServiceClasses(ProviderServices.java:338) at com.sun.jersey.core.spi.component.ProviderServices.getServices(ProviderServices.java:162) at com.sun.jersey.core.spi.factory.MessageBodyFactory.initReaders(MessageBodyFactory.java:176) at com.sun.jersey.core.spi.factory.MessageBodyFactory.init(MessageBodyFactory.java:162) at com.sun.jersey.api.client.Client.init(Client.java:343) at com.sun.jersey.api.client.Client.access$000(Client.java:119) at com.sun.jersey.api.client.Client$1.f(Client.java:192) at com.sun.jersey.api.client.Client$1.f(Client.java:188) at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193) at com.sun.jersey.api.client.Client.&lt;init&gt;(Client.java:188) at com.sun.jersey.api.client.Client.&lt;init&gt;(Client.java:171) at com.sun.jersey.api.client.Client.create(Client.java:683) at org.marvelution.jji.JIRAUtils.createClient(JIRAUtils.java:82) at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(Unknown Source) at java.lang.ThreadLocal.setInitialValue(Unknown Source) at java.lang.ThreadLocal.get(Unknown Source) at org.marvelution.jji.SitesClient.getResource(SitesClient.java:209) at org.marvelution.jji.SitesClient.getResource(SitesClient.java:217) at org.marvelution.jji.SitesClient.getResource(SitesClient.java:213) at org.marvelution.jji.SitesClient.lambda$notifyBuildCompleted$1(SitesClient.java:71) at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) at java.util.stream.AbstractPipeline.copyInto(Unknown Source) at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) at java.util.stream.AbstractPipeline.evaluate(Unknown Source) at java.util.stream.ReferencePipeline.forEach(Unknown Source) at org.marvelution.jji.SitesClient.doWithSites(SitesClient.java:201) at org.marvelution.jji.SitesClient.doWithSites(SitesClient.java:197) at org.marvelution.jji.SitesClient.notifyBuildCompleted(SitesClient.java:69) at org.marvelution.jji.listener.BuildListener.onCompleted(BuildListener.java:45) at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:208) at org.jenkinsci.plugins.workflow.job.WorkflowRun.finish(WorkflowRun.java:625) at org.jenkinsci.plugins.workflow.job.WorkflowRun.access$800(WorkflowRun.java:138) at org.jenkinsci.plugins.workflow.job.WorkflowRun$GraphL.onNewHead(WorkflowRun.java:1045) at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1473) at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:491) at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:38) at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139) at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28) at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68) at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) at java.util.concurrent.FutureTask.run(Unknown Source) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.<span class="code-object">Thread</span>.run(Unknown Source)
</pre>
</div></div>
<p>I use JVM 1.8.0_282.</p>

<p>I assume this is a bug because a class can't be found. </p>

<p>Is there a workarround available (because I don't want to downgrade the whole system)?</p></pre>
</details>
</details>
<details><summary><i>1 attachment</i></summary>

- [multibranch.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-last/refs/heads/main/attachments/56993/multibranch.png)
  > ![multibranch.png](https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-last/refs/heads/main/attachments/56993/multibranch.png)
</details>
