### ISSUE TITLE
[JENKINS-72834] Sharelib Fail after Upgrade Git Plugin to 5.2.1

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/workflow-cps-plugin#1683]
<p>After Upgrading Git Plugin to 5.2.1, in the global configuration, section "Global Pipeline Libraries", can't show the git commit id.</p>

<p><span class="image-wrap" style=""><img src="https://issues.jenkins.io/secure/attachment/62179/62179_image-2024-03-08-13-16-24-058.png" style="border: 0px solid black" /></span></p>

<p> </p>

<p>Build error as below:<br/>
Loading library shared-library@​master<br/>
java.lang.NoSuchMethodError: 'java.util.List com.cloudbees.plugins.credentials.CredentialsProvider.lookupCredentialsInItem(java.lang.Class, hudson.model.Item, org.springframework.security.core.Authentication, java.util.List)'<br/>
	at jenkins.plugins.git.AbstractGitSCMSource.getCredentials(AbstractGitSCMSource.java:1291)<br/>
	at jenkins.plugins.git.AbstractGitSCMSource.retrieve(AbstractGitSCMSource.java:859)<br/>
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:635)<br/>
	at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.lambda$retrieve$0(SCMSourceRetriever.java:75)<br/>
	at org.jenkinsci.plugins.workflow.libs.SCMBasedRetriever.retrySCMOperation(SCMBasedRetriever.java:222)<br/>
	at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.retrieve(SCMSourceRetriever.java:75)<br/>
	at org.jenkinsci.plugins.workflow.libs.LibraryAdder.retrieve(LibraryAdder.java:264)<br/>
	at org.jenkinsci.plugins.workflow.libs.LibraryAdder.add(LibraryAdder.java:151)</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=hudson">hudson</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-72834" target="_blank">Sharelib Fail after Upgrade Git Plugin to 5.2.1</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>component(s)</b>: workflow-cps-plugin
<li><b>resolution</b>: Not A Defect
<li><b>resolved</b>: 2024-04-12T08:19:17+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 2025-12-07
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After Upgrading Git Plugin to 5.2.1, in the global configuration, section "Global Pipeline Libraries", can't show the git commit id.</p>

<p><span class="image-wrap" style=""><img src="https://issues.jenkins.io/secure/attachment/62179/62179_image-2024-03-08-13-16-24-058.png" style="border: 0px solid black" /></span></p>

<p> </p>

<p>Build error as below:
Loading library shared-library@master
java.lang.NoSuchMethodError: 'java.util.List com.cloudbees.plugins.credentials.CredentialsProvider.lookupCredentialsInItem(java.lang.Class, hudson.model.Item, org.springframework.security.core.Authentication, java.util.List)'
	at jenkins.plugins.git.AbstractGitSCMSource.getCredentials(AbstractGitSCMSource.java:1291)
	at jenkins.plugins.git.AbstractGitSCMSource.retrieve(AbstractGitSCMSource.java:859)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:635)
	at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.lambda$retrieve$0(SCMSourceRetriever.java:75)
	at org.jenkinsci.plugins.workflow.libs.SCMBasedRetriever.retrySCMOperation(SCMBasedRetriever.java:222)
	at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.retrieve(SCMSourceRetriever.java:75)
	at org.jenkinsci.plugins.workflow.libs.LibraryAdder.retrieve(LibraryAdder.java:264)
	at org.jenkinsci.plugins.workflow.libs.LibraryAdder.add(LibraryAdder.java:151)</p></pre>
</details>
</details>
<details><summary><i>1 attachment</i></summary>

- [image-2024-03-08-13-16-24-058.png](https://issues.jenkins.io/secure/attachment/62179/image-2024-03-08-13-16-24-058.png)
  > ![image-2024-03-08-13-16-24-058.png](https://issues.jenkins.io/secure/attachment/62179/image-2024-03-08-13-16-24-058.png)
</details>
